### ISSUE TITLE
Brotli for WOFF2 support

### ISSUE THREAD

**Issue by Ciantic** [hexops/freetype#4]
Add [Google's Brotli](https://github.com/google/brotli) as an option so that FreeType has WOFF2 support.

I did [Freetype WASM library](https://github.com/Ciantic/freetype-wasm), but I'm sorely disappointed with emscripten because it produces outdated JS wrapper with 6000 lines of code littered with XMLHtttpRequest etc. 

I first experiment without Brotli support if Zig is a good tool for packaging WASM library, and will be happy to provide this feature if Zig is a good tool for WASM.

Currently I [compile FreeType like this](https://github.com/Ciantic/freetype-wasm/blob/master/build_freetype.sh) for wasm using emscripten:

```
emcmake cmake \
        -D BROTLIDEC_LIBRARIES="$EMSDK/upstream/emscripten/cache/sysroot/lib/libbrotlidec-static.a" \
        -D FT_DISABLE_ZLIB=TRUE \
        -D FT_DISABLE_BZIP2=TRUE \
        -D FT_DISABLE_PNG=TRUE \
        -D FT_DISABLE_HARFBUZZ=TRUE \
        -D FT_REQUIRE_BROTLI=TRUE \
        ..
```

And [brotli like this](https://github.com/Ciantic/freetype-wasm/blob/master/build_brotli.sh):

```
git clone https://github.com/google/brotli
mkdir -p brotli/buildc
(
    cd brotli/buildc || exit
    emcmake cmake ..
    emmake make
    emmake make install
)
```

**Comment by slimsag** [comment]
cc @alichraghi maybe we should consider brotli for WOFF2 fonts ?

**Comment by alichraghi** [comment]
should we build brotli from source or add it to `system-sdk-<os>`?

**Comment by slimsag** [comment]
From source for sure. The SDKs are meant to be very minimal.

**Comment by slimsag** [comment]
Fixed via https://github.com/hexops/mach-freetype/commit/fdd1b28a4ed233ccf91e10fe3d5ef00df2d4d6c4

**Comment by slimsag** [comment]
FYI: In the future issues like this should go in https://github.com/hexops/mach so we have better visibility into them. I will close this issue tracker.
